definitions:     
  env_vars: &env_vars
    S3_BUCKET_NAME: cmswiftwhitelabel
    APP_ICON: AppIcon.appiconset
    HEADER: header.imageset
    LAUNCH_SCREEN: launchScreenColor.colorset

workflows:
    ios-workflow:
      name: iOS Workflow
      instance_type: mac_mini_m4
      labels:
        - ${CLIENT_ID}
      environment:
        xcode: 26
        cocoapods: default
        vars:
          <<: *env_vars
          XCODE_SCHEME: swiftlabel
          CLIENT_ID: "_"

        groups:
          - aws_credentials
      cache:
        cache_paths:
          - $HOME/Library/Developer/Xcode/DerivedData/CompilationCache.noindex
          # - $HOME/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
          # - Users/builder/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: 'main'
            include: true
            source: true
      scripts:
        - name: Customize app assets
          script: make fetch-assets set-app-name set-bundle-id set-launch-color set-header-image set-config-plist

        - name: iOS code signing
          script: |
            keychain initialize
            app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE
            keychain add-certificates
            xcode-project use-profiles
        - name: Increment build number
          script: |
            agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1))
        - name: Build ipa for distribution
          script: |
            xcode-project build-ipa \
              --project "${XCODE_SCHEME}.xcodeproj" \
              --scheme "${XCODE_SCHEME}" \
              --archive-xcargs "COMPILATION_CACHE_ENABLE_CACHING=True"
      artifacts:
        - build/ios/ipa/*.ipa
        - /tmp/xcodebuild_logs/*.log
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      publishing:
        app_store_connect:
          api_key: $APP_STORE_CONNECT_PRIVATE_KEY
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID


