workflows:
  ios-workflow:
    name: iOS Workflow
    labels:
      - ${CLIENT_ID}
    environment:
      xcode: 26
      vars:
        XCODE_SCHEME: swiftlabel
        CLIENT_ID: "_"
      groups:
        - aws_credentials
        - app_customization
    cache:
      cache_paths:
        - $HOME/Library/Developer/Xcode/DerivedData/CompilationCache.noindex
        - $HOME/Library/Developer/Xcode/DerivedData/ModuleCache.noindex
    scripts:
      - make customize-app
      - make ios-code-sign
      - make increment-build-number
      - make build-ipa
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID


